spring:
  application:
    name: booking
  datasource:
    url: jdbc:postgresql://localhost:5432/airline
    username: postgres
    password: "AMD99#gch"
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update  # use 'validate' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  redis:
    host: localhost
    port: 6379
    timeout: 60000ms
    om:
      enabled: true
      repositories:
        base-packages: com.axiom.booking.repository

llm:
  gemini:
    # If LangChain4j requires API key or endpoint (set as env variable)
    api-key: "AIzaSyA5NGOXLDWO-_WstVqcOvn0Ubz66ZJ0Qqs"
    model: "gemini-2.5-flash"
    max-tokens: 1000
    temperature: 0.7

logging:
  level:
    root: INFO
    com.axiom.booking: DEBUG
